### ISSUE TITLE
Would you consider downgrading the build requirement to Java 8?

### ISSUE THREAD

**Issue by jimshowalter** [sfuhrm/openssl4j#5]
There are only three places in the code that use Java 9+ language features.

Two of them are due to using Set.of, which can be eplaced by new HashSet<>(Arrays.asList(<foo>)) at a small cost to readability.

The other is because you are calling java.security.Provider(String name, String versionStr, String info) in OpenSSL4JProvider's constructor, but the overload with String versionStr wasn't added until Java 9.

We are unfortunately unable to use anything newer than Java 8.

**Comment by sfuhrm** [comment]
Hi @jimshowalter ,
thanks for your question! Sure, if you're willing to supply a PR then I can live with Java 8 at least for some years ;).
The project is at the moment limited to message digests, so if you are satisfied with that then go for it!
Stephan
